[package]
name = "run"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
wasm-run = { path = "../../..", default-features = false, features = [] }
