name: main

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 1 * *

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Get main commit hash
        id: main_commit
        run: echo "::set-output name=hash::$(git rev-parse origin/main)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache target, rustup and cargo registry
        id: cache-target
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/bin
            target
            examples/backend-and-frontend/target
          key: main-${{ steps.main_commit.outputs.hash }}

      - name: Install target wasm32-unknown-unknown (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
