name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Cache target
        id: cache-target
        uses: actions/cache@v2
        with:
          path: |
            target
            examples/backend-and-frontend/target
          key: ${{ github.event.issue.number }}-${{ runner.os }}-pr
          restore-keys: main

      - name: Install target wasm32-unknown-unknown
        uses: actions-rs/toolchain@v1
        with:
            target: wasm32-unknown-unknown

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
