name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CARGO_TARGET_DIR: ${{ env.GITHUB_WORKSPACE }}/target
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  test-linux:
    runs-on: ubuntu-latest
    env:
      CARGO_TARGET_DIR: ${{ env.GITHUB_WORKSPACE }}/target
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: cargo test -- examples
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace -- examples

      - name: cargo test -- test_crates
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace -- test_crates

  test-windows:
    needs: [lint, test-linux]
    runs-on: windows-latest
    env:
      CARGO_TARGET_DIR: ${{ env.GITHUB_WORKSPACE }}\target
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: cargo test -- examples
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace -- examples

      - name: cargo test -- test_crates
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace -- test_crates

  test-osx-x86:
    needs: [lint, test-linux]
    runs-on: macos-latest
    env:
      CARGO_TARGET_DIR: ${{ env.GITHUB_WORKSPACE }}/target
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: cargo test -- examples
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace -- examples

      - name: cargo test -- test_crates
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace -- test_crates
